public class merhaba{

    // Sınıfın ana metodu
    public static void main(String[] args) {
        // Merhaba Dünya yazısını ekrana yazdır
        System.debug('Merhaba Dünya!');
        
        // Başka bir metodu çağırabiliriz
        selamVer();
    }

    // Başka bir metot
    public static void selamVer() {
        // Selam ver yazısını ekrana yazdır
        System.debug('Selam ver!');
    }
}